server:
  port: 1234
  servlet:
    context-path: /lms
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/LMS_DB
    username:****  #changed as per Local DB
    password:****  #changed as per Local DB
  jackson.deserialization.fail-on-unknown-properties: true
  jackson.serialization.fail-on-empty-beans: false  
  mvc.hiddenmethod.filter.enabled: true
  main.allow-bean-definition-overriding: true
  #hibernate ddl Auto for CURDOperations
  jpa.hibernate.ddl-auto: update


#File related Configurations
  
  Spring :
  http :
   multipart :
     enabled = true
               
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:8MB}
      max-request-size: ${MAX_REQUEST_SIZE:8MB}
      
  project:
  image: images/
      

logging:
  file:
    name: lmsservice.log
    path: ./


